version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      # Required
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEBUG=${DEBUG:-true}
      
      # Optional AI APIs
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      
      # Database
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./timely.db}
      
      # App Configuration
      - APP_NAME=${APP_NAME:-Timely}
      - APP_VERSION=${APP_VERSION:-1.0.0}
      
      # Authentication (Optional)
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-change-this-in-production}
      
      # Vector Database
      - CHROMA_DB_PATH=${CHROMA_DB_PATH:-./data/vectors/chroma_db}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-all-MiniLM-L6-v2}
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3